In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from collections import Counter

from sklearn.ensemble import IsolationForest
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler

In [2]:
training_start = 1
training_end = 3

test_start =4
test_end =5

In [3]:
# Define the mapping of attack types to integer keys
attack_type_map = {
    'Benign': 0,
    'DoS': 1,
    'scanning': 2,
    'DDoS': 3,
    'xss': 4,
    'Bot': 5,
    'Reconnaissance': 6,
    'password': 7,
    'Fuzzers': 8,
    'injection': 9,
    'Theft': 10,
    'Brute Force': 11,
    'Infilteration': 12,
    'Exploits': 13,
    'Generic': 14,
    'Analysis': 15,
    'Backdoor': 16,
    'mitm': 17,
    'Shellcode': 18,
    'ransomware': 19,
    'Worms': 20
}

drop_column={
    'Dataset',
    'IPV4_SRC_ADDR',
    'IPV4_DST_ADDR',
    'L7_PROTO',
    'SRC_TO_DST_SECOND_BYTES',
    'DST_TO_SRC_SECOND_BYTES',
    'FTP_COMMAND_RET_CODE',

}
drop_purposed_column= {
    'Label',
    'Attack'
}


In [4]:
dataset = pd.read_csv('dataset-v2/part_1.csv')
dataset.drop(columns=drop_column, inplace=True)
dataset.drop(columns=drop_purposed_column, inplace=True)
# dataset['Attack'] = dataset['Attack'].map(attack_type_map)

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850145 entries, 0 to 850144
Data columns (total 37 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   L4_SRC_PORT                  850145 non-null  int64
 1   L4_DST_PORT                  850145 non-null  int64
 2   PROTOCOL                     850145 non-null  int64
 3   IN_BYTES                     850145 non-null  int64
 4   IN_PKTS                      850145 non-null  int64
 5   OUT_BYTES                    850145 non-null  int64
 6   OUT_PKTS                     850145 non-null  int64
 7   TCP_FLAGS                    850145 non-null  int64
 8   CLIENT_TCP_FLAGS             850145 non-null  int64
 9   SERVER_TCP_FLAGS             850145 non-null  int64
 10  FLOW_DURATION_MILLISECONDS   850145 non-null  int64
 11  DURATION_IN                  850145 non-null  int64
 12  DURATION_OUT                 850145 non-null  int64
 13  MIN_TTL                      

In [6]:
list_attributes = dataset.columns

In [7]:
print(list_attributes)

Index(['L4_SRC_PORT', 'L4_DST_PORT', 'PROTOCOL', 'IN_BYTES', 'IN_PKTS',
       'OUT_BYTES', 'OUT_PKTS', 'TCP_FLAGS', 'CLIENT_TCP_FLAGS',
       'SERVER_TCP_FLAGS', 'FLOW_DURATION_MILLISECONDS', 'DURATION_IN',
       'DURATION_OUT', 'MIN_TTL', 'MAX_TTL', 'LONGEST_FLOW_PKT',
       'SHORTEST_FLOW_PKT', 'MIN_IP_PKT_LEN', 'MAX_IP_PKT_LEN',
       'RETRANSMITTED_IN_BYTES', 'RETRANSMITTED_IN_PKTS',
       'RETRANSMITTED_OUT_BYTES', 'RETRANSMITTED_OUT_PKTS',
       'SRC_TO_DST_AVG_THROUGHPUT', 'DST_TO_SRC_AVG_THROUGHPUT',
       'NUM_PKTS_UP_TO_128_BYTES', 'NUM_PKTS_128_TO_256_BYTES',
       'NUM_PKTS_256_TO_512_BYTES', 'NUM_PKTS_512_TO_1024_BYTES',
       'NUM_PKTS_1024_TO_1514_BYTES', 'TCP_WIN_MAX_IN', 'TCP_WIN_MAX_OUT',
       'ICMP_TYPE', 'ICMP_IPV4_TYPE', 'DNS_QUERY_ID', 'DNS_QUERY_TYPE',
       'DNS_TTL_ANSWER'],
      dtype='object')


In [8]:
dataset.drop(columns= list_attributes[0], inplace=True)

In [9]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850145 entries, 0 to 850144
Data columns (total 36 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   L4_DST_PORT                  850145 non-null  int64
 1   PROTOCOL                     850145 non-null  int64
 2   IN_BYTES                     850145 non-null  int64
 3   IN_PKTS                      850145 non-null  int64
 4   OUT_BYTES                    850145 non-null  int64
 5   OUT_PKTS                     850145 non-null  int64
 6   TCP_FLAGS                    850145 non-null  int64
 7   CLIENT_TCP_FLAGS             850145 non-null  int64
 8   SERVER_TCP_FLAGS             850145 non-null  int64
 9   FLOW_DURATION_MILLISECONDS   850145 non-null  int64
 10  DURATION_IN                  850145 non-null  int64
 11  DURATION_OUT                 850145 non-null  int64
 12  MIN_TTL                      850145 non-null  int64
 13  MAX_TTL                      

In [10]:
# import scipy.stats as stats
# 
# # Histogram
# sns.histplot(dataset, kde=True)
# plt.title("Histogram")
# plt.show()

In [11]:
# Q-Q Plot
# stats.probplot(dataset, dist="norm", plot=plt)
# plt.title("Q-Q Plot")
# plt.show()

In [12]:

scaler = StandardScaler()
data_normalized = scaler.fit_transform(dataset)
print(data_normalized)

[[-0.30654098 -0.74821467 -0.0077353  ... -0.3387917  -0.13934468
  -0.00167769]
 [-0.30654098 -0.74821467 -0.00962603 ... -0.3387917  -0.13934468
  -0.00167769]
 [-0.21684028 -0.74821467 -0.01281326 ... -0.3387917  -0.13934468
  -0.00167769]
 ...
 [-0.30654098  1.19632187 -0.01151676 ... -0.3387917  -0.13934468
  -0.00167769]
 [-0.30654098 -0.74821467 -0.00854561 ... -0.3387917  -0.13934468
  -0.00167769]
 [-0.30654098 -0.74821467 -0.00634426 ... -0.3387917  -0.13934468
  -0.00167769]]


## 1. Data Preprocessing

In [17]:
total_counts = Counter()

label_count= Counter()
for i in range(1,90):
    data = pd.read_csv(f'dataset-v2/part_{i}.csv')
    num_type = Counter(data['Attack'])
    label_type= Counter(data['Label'])
    total_counts.update(num_type)
    label_count.update(label_type)
print("\nTổng số lượng của mỗi phần tử trong tất cả các file:", total_counts)
print("\nTổng số lượng của mỗi nhãn trong tất cả các file:", label_count)


KeyboardInterrupt: 

In [ ]:
plt.figure(figsize=(20,10))
plt.bar(total_counts.keys(), total_counts.values())
plt.show()
plt.savefig('total_counts.png')


In [ ]:
plt.figure(figsize=(20,10))
plt.bar(label_count.keys(), label_count.values())
plt.show()
plt.savefig('label_count.png')


In [34]:
IsolationForest_model= IsolationForest(max_features=0.5)


In [35]:
from sklearn.feature_selection import SelectFromModel, SelectKBest, f_classif

In [36]:
def train_data(data):
    data.drop(columns=drop_column, inplace=True)
    # data['Attack'] = data['Attack'].map(attack_type_map)
    label = data['Label']
    # attack = data['Attack']
    label.replace(0,-1, inplace=True)
    data.drop(columns=drop_purposed_column, inplace=True)
    
    scaler = StandardScaler()
    data_normalized = scaler.fit_transform(data)
    IsolationForest_model.fit(data_normalized)
    IsolationForest_model.decision_function(data_normalized)
    data['scores'] = IsolationForest_model.decision_function(data_normalized)


In [37]:
train_url =[f'dataset-v2/part_{i}.csv' for i in range(training_start,training_end)]
test_url =[f'dataset-v2/part_{i}.csv' for i in range(test_start,test_end)]

In [38]:
for train_path in train_url:
    data = pd.read_csv(train_path)
    train_data(data)

In [39]:
prediction =[]
original_result=[]

for test_path in test_url:
    test = pd.read_csv(test_path)
    test.drop(columns=drop_column, inplace=True)
    # test['Attack'] = test['Attack'].map(attack_type_map)
    label = test['Label']
    
    attack = test['Attack']
    # label.replace(1,-1, inplace=True)
    label.replace(0,-1, inplace=True)
    test.drop(columns=drop_purposed_column, inplace=True)
    
    
    scaler = StandardScaler()
    test_normalized = scaler.fit_transform(test)
    
    y_pred = IsolationForest_model.predict(test_normalized)
    test['Label']=label
    test['prediction']=y_pred
    prediction.append(y_pred)
    original_result.append(label)
    

In [40]:
#convert to 1D array
prediction = np.concatenate(prediction)
original_result = np.concatenate(original_result)

In [41]:
print(len(original_result))

850082


In [42]:
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix


In [43]:
# from docx import Document

# Calculate metrics
acc = accuracy_score(original_result, prediction)
f1 = f1_score(original_result, prediction)
roc_auc = roc_auc_score(original_result, prediction)
cm = confusion_matrix(original_result, prediction)

# Create a new Document
# doc = Document()
# 
# # Add a title
# doc.add_heading('Model Evaluation Results', level=1)
# 
# # Add accuracy
# doc.add_heading('Accuracy', level=2)
# doc.add_paragraph(f"IF acc = {acc}")
# 
# # Add F1 score
# doc.add_heading('F1 Score', level=2)
# doc.add_paragraph(f"-IF f1 = {f1}")
# 
# # Add ROC AUC
# doc.add_heading('ROC AUC', level=2)
# doc.add_paragraph(f"-IF roc auc = {roc_auc}")
# 
# # Add confusion matrix
# doc.add_heading('Confusion Matrix', level=2)
# cm_text = '\n'.join(['\t'.join(map(str, row)) for row in cm])
# doc.add_paragraph(cm_text)
# 
# # Save the document
# doc.save('model_evaluation_results.docx')

In [44]:
print(acc)

0.7291755383598288


In [ ]:
import seaborn as sns

# Create a heatmap
plt.figure(figsize=(10, 7))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')

# Add labels and title
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix Heatmap')

# Save the heatmap as a PNG file
plt.savefig('confusion_matrix_heatmap.png')

# Show the heatmap
plt.show()

# feature selection

In [17]:
from sklearn.decomposition import PCA



In [21]:
def train_and_evaluate_feature_selection(n_component):
    IsolationForest_evaluate_model = IsolationForest()
    pca = None  # Để lưu PCA
    scaler = None  # Để lưu StandardScaler
    
    def train_data(data):
        nonlocal pca, scaler
        # Xóa các cột không cần thiết
        data.drop(columns=drop_column, inplace=True)
        label = data['Label']
        data.drop(columns=drop_purposed_column, inplace=True)
        
        # Áp dụng PCA
        pca = PCA(n_components=n_component)  # Giữ 95% phương sai
        data_reduced = pca.fit_transform(data)
        
        # Chuẩn hóa dữ liệu
        scaler = StandardScaler()
        data_normalized = scaler.fit_transform(data_reduced)
        
        # Chuyển đổi nhãn
        label.replace(0, -1, inplace=True)
        
        # Huấn luyện Isolation Forest
        IsolationForest_evaluate_model.fit(data_normalized)
    
    for train_path in train_url:
        data = pd.read_csv(train_path)
        train_data(data)
    
    prediction = []
    original_result = []
    
    def test_data(test):
        nonlocal pca, scaler
        # Xóa các cột không cần thiết
        test.drop(columns=drop_column, inplace=True)
        label = test['Label']
        label.replace(0, -1, inplace=True)
        test.drop(columns=drop_purposed_column, inplace=True)
        
        # Áp dụng PCA và chuẩn hóa
        test_reduced = pca.transform(test)  # Áp dụng PCA từ tập train
        test_normalized = scaler.transform(test_reduced)  # Áp dụng scaler từ tập train
        
        # Dự đoán
        y_pred = IsolationForest_evaluate_model.predict(test_normalized)
        return y_pred, label
    
    for test_path in test_url:
        test = pd.read_csv(test_path)
        y_pred, label = test_data(test)
        prediction.append(y_pred)
        original_result.append(label)
    
    # Ghép kết quả
    prediction = np.concatenate(prediction)
    original_result = np.concatenate(original_result)
    
    # Đánh giá mô hình
    acc = accuracy_score(original_result, prediction)
    f1 = f1_score(original_result, prediction)
    roc_auc = roc_auc_score(original_result, prediction)
    cm = confusion_matrix(original_result, prediction)
    
    return acc, f1, roc_auc, cm

In [23]:
from document import Document

# acc, f1, roc_auc, cm = train_and_evaluate_feature_selection()
test =[0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]
for i in test:
    acc, f1, roc_auc, cm = train_and_evaluate_feature_selection(i)
    print(f"n_component = {i}")
    print(f"Accuracy: {acc}")
    print(f"F1 Score: {f1}")
    print(f"ROC AUC: {roc_auc}")
    print(f"Confusion Matrix:\n{cm}")
# save to the docx file
#     doc = Document()
#     doc.a
#     doc.add_heading('Model Evaluation Results', level=1)
#     doc.add_heading('Feature Selection', level=2)
#     doc.add_heading('PCA', level=3)
#     doc.add_paragraph(f"PCA n_component = {i}")
#     doc.add_paragraph(f"Accuracy: {acc}")
#     doc.add_paragraph(f"F1 Score: {f1}")
#     doc.add_paragraph(f"ROC AUC: {roc_auc}")
#     doc.add_paragraph(f"Confusion Matrix:\n{cm}")
#     doc.save(f'model_evaluation_results_fs{i}.docx')


n_component = 0.2
Accuracy: 0.7362395627715914
F1 Score: 0.8278736346915024
ROC AUC: 0.6278625749618426
Confusion Matrix:
[[ 86655 194058]
 [ 30160 539209]]
n_component = 0.3
Accuracy: 0.755477706856515
F1 Score: 0.8369187606503667
ROC AUC: 0.6622646663787781
Confusion Matrix:
[[108848 171865]
 [ 35999 533370]]
n_component = 0.4
Accuracy: 0.7296743137720831
F1 Score: 0.8241229644517136
ROC AUC: 0.6186568699645665
Confusion Matrix:
[[ 81888 198825]
 [ 30974 538395]]
n_component = 0.5
Accuracy: 0.7349020447439188
F1 Score: 0.8269305057111282
ROC AUC: 0.6265895851043113
Confusion Matrix:
[[ 86351 194362]
 [ 30993 538376]]
n_component = 0.6
Accuracy: 0.7384605249846485
F1 Score: 0.8287141970067935
ROC AUC: 0.6324634717659433
Confusion Matrix:
[[ 89914 190799]
 [ 31531 537838]]
n_component = 0.7
Accuracy: 0.7452857489042234
F1 Score: 0.8324722048139638
ROC AUC: 0.6426687393114774
Confusion Matrix:
[[ 95573 185140]
 [ 31388 537981]]
n_component = 0.8
Accuracy: 0.7316682390639961
F1 Score: 0.

In [ ]:
#
    
    

In [28]:
print(acc)
print(f1)
print(roc_auc)
print(cm)

0.7423436797861853
0.8315180978681015
0.6359456415796485
[[ 90560 190153]
 [ 28876 540493]]


In [24]:

def train_and_evaluate_feature_selection_with_other_estimator(n_estimator,n_component):
    IsolationForest_evaluate_model = IsolationForest(n_estimators=n_estimator)
    pca = None  # Để lưu PCA
    scaler = None  # Để lưu StandardScaler
    
    def train_data(data):
        nonlocal pca, scaler
        # Xóa các cột không cần thiết
        data.drop(columns=drop_column, inplace=True)
        label = data['Label']
        data.drop(columns=drop_purposed_column, inplace=True)
        
        # Áp dụng PCA
        pca = PCA(n_components=n_component)  # Giữ số thành phần mong muốn
        data_reduced = pca.fit_transform(data)
        
        # Chuẩn hóa dữ liệu
        scaler = StandardScaler()
        data_normalized = scaler.fit_transform(data_reduced)
        
        # Chuyển đổi nhãn
        label.replace(0, -1, inplace=True)
        
        # Huấn luyện Isolation Forest
        IsolationForest_evaluate_model.fit(data_normalized)
    
    for train_path in train_url:
        data = pd.read_csv(train_path)
        train_data(data)
    
    prediction = []
    original_result = []
    
    def test_data(test):
        nonlocal pca, scaler
        # Xóa các cột không cần thiết
        test.drop(columns=drop_column, inplace=True)
        label = test['Label']
        label.replace(0, -1, inplace=True)
        test.drop(columns=drop_purposed_column, inplace=True)
        
        # Áp dụng PCA và chuẩn hóa
        test_reduced = pca.transform(test)  # Áp dụng PCA từ tập train
        test_normalized = scaler.transform(test_reduced)  # Áp dụng scaler từ tập train
        
        # Dự đoán
        y_pred = IsolationForest_evaluate_model.predict(test_normalized)
        return y_pred, label
    
    for test_path in test_url:
        test = pd.read_csv(test_path)
        y_pred, label = test_data(test)
        prediction.append(y_pred)
        original_result.append(label)
    
    # Ghép kết quả
    prediction = np.concatenate(prediction)
    original_result = np.concatenate(original_result)
    
    # Đánh giá mô hình
    acc = accuracy_score(original_result, prediction)
    f1 = f1_score(original_result, prediction)
    roc_auc = roc_auc_score(original_result, prediction)
    cm = confusion_matrix(original_result, prediction)
    
    return acc, f1, roc_auc, cm


In [1]:
test =[0.4]
estimator=[1500]
for i in test:
    for j in estimator:
        acc, f1, roc_auc, cm = train_and_evaluate_feature_selection_with_other_estimator(j,i)
        print(f"n_component = {i}")
        print(f"n_estimator = {j}")
        print(f"Accuracy: {acc}")
        print(f"F1 Score: {f1}")
        print(f"ROC AUC: {roc_auc}")
        print(f"Confusion Matrix:\n{cm}")
        print()
        # doc = Document()
        # doc.add_heading('Model Evaluation Results', level=1)
        # doc.add_heading('Feature Selection', level=2)
        # doc.add_heading('PCA', level=3)
        # doc.add_paragraph(f"PCA n_component = {i}")
        # doc.add_paragraph(f"n_estimator = {j}")
        # doc.add_paragraph(f"Accuracy: {acc}")
        # doc.add_paragraph(f"F1 Score: {f1}")
        # doc.add_paragraph(f"ROC AUC: {roc_auc}")
        # doc.add_paragraph(f"Confusion Matrix:\n{cm}")
        # doc.save(f'model_evaluation_results_fs{i}_estimator{j}.docx')
    



NameError: name 'train_and_evaluate_feature_selection_with_other_estimator' is not defined